# Generated by Django 2.1.7 on 2019-03-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Repassword',
            field=models.CharField(max_length=256),
        ),
    ]
