# Generated by Django 2.1.7 on 2019-03-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0005_registration_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
