# Generated by Django 2.1.7 on 2019-03-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0006_auto_20190306_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
