# Generated by Django 2.1.7 on 2019-03-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0010_auto_20190308_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Email',
            new_name='Email1',
        ),
    ]
