# Generated by Django 2.1.7 on 2019-03-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0011_auto_20190308_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Email1',
            new_name='Email',
        ),
    ]
