# Generated by Django 2.1.7 on 2019-03-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0012_auto_20190308_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
