# Generated by Django 2.1.7 on 2019-03-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0014_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sub',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='teacher',
            name='branch',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
