# Generated by Django 2.1.7 on 2019-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0015_auto_20190311_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='teafollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('sub', models.CharField(max_length=30)),
            ],
        ),
    ]
