# Generated by Django 2.1.7 on 2019-03-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0016_teafollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='teafollower',
            name='student_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
