# Generated by Django 2.1.7 on 2019-03-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0019_auto_20190314_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='teacher_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
