# Generated by Django 2.1.7 on 2019-03-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0020_comment_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('follower_id', models.IntegerField()),
                ('twit', models.TextField(max_length=100)),
            ],
        ),
    ]
