# Generated by Django 2.1.7 on 2019-03-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0021_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='userprofile',
        ),
    ]
