# Generated by Django 2.1.7 on 2019-03-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0023_remove_userprofile_twit'),
    ]

    operations = [
        migrations.CreateModel(
            name='twit1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Twit', models.TextField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
