# Generated by Django 2.1.7 on 2019-03-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0026_auto_20190318_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('follower_id', models.IntegerField()),
                ('Twit', models.TextField(max_length=200)),
            ],
        ),
    ]
