# Generated by Django 2.1.7 on 2019-03-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0028_auto_20190320_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referenced_id',
        ),
        migrations.AddField(
            model_name='twit1',
            name='referenced_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
