# Generated by Django 2.1.7 on 2019-03-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0030_create_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_group',
            name='member_no',
        ),
    ]
