# Generated by Django 2.1.7 on 2019-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0031_remove_create_group_member_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_group_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('member_no', models.IntegerField()),
            ],
        ),
    ]
