# Generated by Django 2.1.7 on 2019-03-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0032_add_group_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_group_member',
            name='group_name',
        ),
        migrations.AddField(
            model_name='add_group_member',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
