# Generated by Django 2.1.7 on 2019-04-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0033_auto_20190329_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_group_member',
            name='group_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
