# Generated by Django 2.1.7 on 2019-04-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0035_add_group_member_group_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_group_member',
            name='Group_comment',
        ),
    ]
