# Generated by Django 2.1.7 on 2019-04-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0036_remove_add_group_member_group_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('mem_id', models.IntegerField()),
            ],
        ),
    ]
