# Generated by Django 2.1.7 on 2019-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0037_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
